# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "rhel-server-7:gui:ose-3.1:vagrant-virtualbox"

  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--cpuexecutioncap", "80"]
    vb.customize ["modifyvm", :id, "--vram", "16"]
    vb.customize ["modifyvm", :id, "--ostype", "RedHat_64"]
    vb.memory = 8192
    vb.name = "OSE3.1"
    #vb.gui = true
  end

  if Vagrant.has_plugin?('vagrant-registration')
    config.registration.skip = true
  end

  config.vm.synced_folder './', '/vagrant', type: 'rsync', disabled: true
  #config.vm.synced_folder '../', '/mnt/vagrant', type: 'rsync'

  #Always add rcm-img-docker to the /etc/hosts file
  config.vm.provision "shell", inline: "sudo sed -i \"/^EOF$/i 10.16.48.187 rcm-img-docker01.build.eng.bos.redhat.com\" /etc/NetworkManager/dispatcher.d/99-hosts && sudo systemctl restart network"

  # config.vm.provision "shell", inline: <<-SHELL
  #   sudo systemctl stop docker > /dev/null 2>&1
  #   sudo groupadd docker > /dev/null 2>&1
  #   sudo usermod -a -G docker vagrant
  #   sudo chown root:docker /var/run/docker.sock
  #   echo \"DOCKER_NETWORK_OPTIONS='-H tcp://0.0.0.0:2375 -H unix:///var/run/docker.sock'\" | sudo tee /etc/sysconfig/docker-network > /dev/null
  #
  #   # Adding internal docker image repo to the host file (Remove when available public)

  #
  #   #The following line will check if rcm-im-docker01 exists in the dhcp hook otherwise it will add it.
  #    echo "10.16.48.187 rcm-img-docker01.build.eng.bos.redhat.com' /etc/dhcp/dhclient-eth0-up-hooks
  #
  #   sudo systemctl enable docker && sudo systemctl start docker
  #   echo 'Run:\n export DOCKER_HOST=127.0.0.1:2375 && unset DOCKER_CERT_PATH && unset DOCKER_TLS_VERIFY\nto use docker on the host machine'
  #
  # SHELL

  config.vm.network "forwarded_port", guest: 8443, host: 8443, auto_correct: true
  config.vm.network "forwarded_port", guest: 80, host: 80, auto_correct: true
end
